version: '3.8'

services:
  bioacustic:
    build: .
    container_name: bioacustic-app
    ports:
      - "8000:80"
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    environment:
      - TZ=America/Sao_Paulo
    labels:
      - "com.bioacustic.description=Classificador de Anf√≠bios"
      - "com.bioacustic.version=1.0"
    networks:
      - bioacustic-network

networks:
  bioacustic-network:
    driver: bridge
